# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter Action

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup the flutter environment.
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.22.4'
    - name: Get flutter dependencies.
      run: flutter pub get
    - name: Build APK
      run: flutter build appbundle --target-platform android-arm,android-arm64,android-x64
    - name: Create Release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ steps.version.outputs.version }}
        tag_name: ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
      on:
        push:
          tags:
            - '*'
    - name: Upload Android App Bundle Artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/app/outputs/bundle/release/app-release.aab
        asset_name: app-release.aab
        asset_content_type: application/zip
    # - name: Run tests for flutter project.
    #   env:
    #       TENANT_SECRET: ${{ secrets.TENANT }}
    #       CLIENT_ID_SECRET: ${{ secrets.CLIENT_ID }}
    #       SCOPE_SECRET: ${{ secrets.SCOPE }}
    #       POLICY_SECRET: ${{ secrets.POLICY }}
    #       TOKEN_IDENTIFIER_SECRET: ${{ secrets.POLICY }}
    #       NONCE_SECRET: ${{ secrets.NONCE }}
    #   run: flutter test
