# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter Action

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # Setup the flutter environment.
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.22.4'
    # Get flutter dependencies.
    - run: flutter pub get
    # Run widget tests for flutter project.
    - run: flutter test
