# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build iOS Release

on:
  push:
#     tags:
#       - '*'

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup the flutter environment.
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.22.4'
    - name: Get flutter dependencies.
      run: flutter pub get
    - name: Build IPA
      run: flutter build ios
